create InitData class for data initialization directly to the databas…
gergelyszanto/mentoring-home-project pull request #10
Opened 2019-04-16 14:39 UTC by adamveszelinov

please review it. Thanks

2019-04-16 22:32 UTC, gergelyszanto commented on build.gradle
> +    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.8'
Why not RestAssured?

2019-04-16 22:41 UTC, gergelyszanto commented on src/test/java/com/mentoring/framework/utils/InitData.java
> +        } catch (UnsupportedEncodingException e) {
You can merge these 3 exceptions into one catch with pipes. You don't need to include the exception's name into the custom log message if you're adding the stacktrace anyways.

2019-04-16 22:47 UTC, gergelyszanto requested changes

2019-04-16 22:47 UTC, gergelyszanto commented on src/test/java/com/mentoring/framework/utils/InitData.java
> +            StringEntity input = new StringEntity(
This is where RestAssured would look much more readable and clean. With RestAssured you can also declare the expected response code, so your tests can fail-fast if the rest call fails.

2019-04-16 22:47 UTC, gergelyszanto commented on src/test/java/com/mentoring/framework/utils/InitData.java
> +        } catch (IOException e) {
I don't see what happens with the request after all the exceptions are caught. If you can't post a user registration due to an exception, your test shouldn't be able to proceed.

2019-04-19 13:38 UTC, adamveszelinov commented on build.gradle
> +    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.8'
I changed the code to RestAssured

2019-04-20 12:55 UTC, gergelyszanto approved these changes

2019-04-20 12:56 UTC, merged