Sky 15 driver manager library
gergelyszanto/mentoring-home-project pull request #28
Opened 2020-07-08 16:01 UTC by adamveszelinov

Please review it. Thanks

2020-07-08 16:02 UTC, adamveszelinov commented
![](https://github.trello.services/images/mini-trello-icon.png) [DriverManager library](https://trello.com/c/7dPHJV2B/15-drivermanager-library)

2020-07-10 06:27 UTC, gergely-szanto-epam commented
Please delete LocalDriverManager as it's not in use anymore

2020-07-10 06:36 UTC, gergely-szanto-epam requested changes
Please delete LocalDriverManager as it's not in use anymore

2020-07-10 12:05 UTC, gergely-szanto-epam approved these changes

2020-09-11 17:15 UTC, merged